[railway]
  plugin = "docker"

[atomic-search]
  dockerfile = "Dockerfile"

[atomic-search.variables]
  NAME = "Atomic Search"
  GRANIAN_HOST = "0.0.0.0"
  GRANIAN_PORT = "8080"
  IMAGE_PROXY = "true"

[atomic-search.health]
  port = 8080
  path = "/healthz"
