services:
  - type: web
    name: atomic-search
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    numInstances: 1
    envVars:
      - key: NAME
        value: "Atomic Search"
      - key: IMAGE_PROXY
        value: "true"
      - key: GRANIAN_HOST
        value: "0.0.0.0"
      - key: GRANIAN_PORT
        value: "8080"
      - key: SECRET_KEY
        generateValue: true
